### ISSUE TITLE
Center boxes on screen?

### ISSUE THREAD

**Issue by casciano** [tamc/Sankey#19]
Hi,

Is there an easy way to modify sankey.js so that the boxes are in the center of the stack?

Instead of the first box in each stack being aligned to the top, is it possible to move the boxes so that the center of each stack is aligned?

Thanks,
Joe

**Comment by tamc** [comment]
Hi Joe

This is the spot that does the y positioning:
https://github.com/tamc/Sankey/blob/master/src/sankey.coffee#L146

But I can’t think of an easy way to achieve what you suggest with this code.

Sorry

Tom

**Comment by casciano** [comment]
I wrote a little function that works in my situation.  Thanks!
