### ISSUE TITLE
The length of name

### ISSUE THREAD

**Issue by xingdouchen** [tamc/Sankey#21]
HI, 
sorry for my english is not well. 
I use Sankey right now,but I have a problem:
Sankey-master\examples\simple

sankey.stack(0,["Top","Bottom"]);
sankey.stack(1,["Merge"]);
sankey.stack(2,["Good","Bad"]);

if the name of "Top" or "Bottom" is too long,maybe "Top" is "1111122222333333Top", 
when I open it on web browsers, just see "22222333333Top".
can you tell me how to fix it?

**Comment by tamc** [comment]
If I understand correctly, then I think that all that is happening is that there is not enough space for the name.

You can adjust the space to the left and right of the sankey to allow more space for a name.

For example, I have done this here: https://github.com/tamc/Sankey/blob/master/examples/alpha.html#L178

**Comment by xingdouchen** [comment]
yes,thank you~~!

**Comment by tamc** [comment]
Great!
