### ISSUE TITLE
Sankey diagram

### ISSUE THREAD

**Issue by anna01021993** [tamc/Sankey#22]
Hey, 

 is it possible to create a (more complex) Sankey diagramm with the RAW tool from density design? I would like to construct a mutidimensional diagramm where the energy consumption of for various consumers and locations can be retraced. At the moment, it is not possible to construct the diagramm the way that the energy fuels are on the left. next to the location, followed by the consumers and contemporaneously be able to retrace the energy consumption. 

Does anyone have an idea or do you know a Person who i could contact?

Thank you in advance!

**Comment by tamc** [comment]
That is a question for the folks at density design - I don't think they use this Sankey diagram library.
